---
title: "BeerStudyShinyApp"
author: "Rashmi Patel"
date: "3/23/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
library(shiny)
library(dplyr)
#install.packages("shinyWidgets")
library(shinyWidgets)
library(ggplot2)
beers = read.csv("https://raw.githubusercontent.com/RashmiAPatel19/SMU_MSDS_6306_CaseStudy1_Spring2021/main/Beers.csv", header = TRUE)
breweries = read.csv("https://raw.githubusercontent.com/RashmiAPatel19/SMU_MSDS_6306_CaseStudy1_Spring2021/main/Breweries.csv", header = TRUE)
beerbrew <- merge(beers,breweries, by.x = "Brewery_id", by.y = "Brew_ID")

state_list <- unique(beerbrew$State)
state_list<-sort(state_list, decreasing=FALSE)


ui <- fluidPage(
  
  # App title ----
  titlePanel("Explore Beer Data"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      #Copy the line below to make a select box 
       selectInput("parameter", label = h3("Parameter Selection"), 
                    choices = list("IBU" = "IBU", "ABV" = "ABV"), 
                    selected = 1),
                    hr(),
                    fluidRow(column(3, verbatimTextOutput("parameter"))),
      
       
        # Copy the line below to make a set of radio buttons
  radioButtons("typeplot", label = h3("Select Type of Plot"),
    choices = list("Histogram" = 1, "Boxplot" = 2), 
    selected = 1),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("typeplot"))), 

  # Copy the chunk below to make a group of checkboxes
  pickerInput("states", label = h3("Select States"), 
    choices = state_list,selected=state_list,multiple=TRUE,options = pickerOptions(
        actionsBox = TRUE)),
  
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("states"))),
  
    # Copy the line below to make a checkbox
  checkboxInput("regression", label = "Add a Regression Line", value = FALSE),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("regression"))),
  
  
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Histogram ----
      plotOutput(outputId = "distPlot1"),
      plotOutput(outputId = "distPlot2")
    )
  )
)


# Define server logic required to draw a histogram ----
server <- function(input, output) {
  
  output$distPlot1 <- renderPlot({
    
    if(input$parameter == "IBU")
    {
      x <- beerbrew %>% filter(State %in% input$states) %>% filter(!is.na(IBU))
      x <- as.vector(x$IBU)
      bins <- seq(min(x), max(x), length.out = 31)
    
      if(input$typeplot == 1){
        hist(x, breaks = bins, 
         xlab = "IBU",
         main = "Histogram of IBU",col = "skyblue", border = "black")
      }
    if(input$typeplot == 2){
        boxplot(x, 
         xlab = "IBU",
         main = "Boxplot of IBU",col = "skyblue", border = "black")
      }
    
    }
    if(input$parameter == "ABV")
    {
      y <- beerbrew %>% filter(State %in% input$states) %>% filter(!is.na(ABV))
      y <- as.vector(y$ABV)
    bins <- seq(min(y), max(y), length.out = 31)
    
      if(input$typeplot == 1){
        hist(y, breaks = bins, col = "maroon", border = "black",
         xlab = "ABV",
         main = "Histogram of ABV")
      }
    if(input$typeplot == 2){
        boxplot(y, 
         xlab = "ABV",
         main = "Boxplot of ABV", col = "maroon", border = "black")
      }
    

        }
  })

    output$distPlot2 <- renderPlot({
      z <- beerbrew %>% filter(State %in% input$states) 
      
      if(input$regression=="FALSE"){
      z %>% ggplot(aes(x=IBU,y=ABV)) + geom_point() +
  labs(title="ABV vs IBU")
      }

      else{
        z %>% ggplot(aes(x=IBU,y=ABV)) + geom_point() + geom_smooth(method='lm') +
  labs(title="ABV vs IBU")}
      
  })
    
}

shinyApp(ui, server,options=list(height=1080,width=1080))
```